<template>
    <div class="faq-container">
      <h1> F.A.Q.</h1>
      <div
        v-for="(faq, index) in faqs"
        :key="index"
        class="faq-item"
        ref="faqItems"
      >
        <button class="pill-button" @click="toggleFaq(index)">
          <span class="plus-icon" v-html="getIcon(index)"></span>
          {{ faq.question }}
        </button>
        <div class="faq-answer" :class="['faq-answer', isActive(index)]">
          <div class="answer-text" v-html="faq.answer"></div>
        </div>
      </div>
    </div>
  </template>
  
  <script setup lang="ts">
  import { ref, onMounted } from 'vue';
  
  const faqs = ref([
    {
      question: "How does Rivue personalize my learning experience?",
      answer:
        "At Rivue, your learning experience is entirely customized to fit you. Your AI tutor adapts lessons to match your learning style and preferences, and creates engaging content based on your interests and motivations. Learn your way, with quizzes and lessons that adapt to you.",
      isOpen: false,
    },
    {
      question:
        "What types of progress tracking and analytics does Rivue offer?",
      answer:
        "Rivue provides comprehensive progress tracking through detailed statistics and graphs. These tools help you monitor your learning journey, track lesson streaks, and see your improvements over time, enabling you to stay motivated and focused.",
      isOpen: false,
    },
    {
      question: "Is everything on Rivue completely true?",
      answer:
        "All the content on Rivue is generated by AI, so it is impossible to guarantee complete factuality. We use models which always have the possibility of hallucinating; however, it is always recommended to double-check important information.",
      isOpen: false,
    },
    {
      question: "What should I do if I encounter a technical issue on Rivue?",
      answer:
        "If you face any technical issues, you can reach out to our support team via the <a href='/contact'>contact form</a> or email us at Discord for common problems.",
      isOpen: false,
    },
  ]);
  
  const faqItems = ref<HTMLElement[]>([]);
  
  onMounted(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add("fade-in");
          }
        });
      },
      { threshold: [0.1] }
    );
  
    faqItems.value.forEach((faqItem) => {
      observer.observe(faqItem);
    });
  });
  
  function toggleFaq(index: number) {
    faqs.value.forEach((faq, i) => {
      if (i !== index) faq.isOpen = false;
    });
    faqs.value[index].isOpen = !faqs.value[index].isOpen;
  }
  
  function isActive(index: number) {
    return faqs.value[index].isOpen ? "open" : "";
  }
  
  function getIcon(index: number) {
    return faqs.value[index].isOpen ? "-" : "+";
  }
  </script>
  
  <style scoped>
  .faq-container {
    margin-top: 2em;
    padding: 0 1em;
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  
  .faq-item {
    display: flex;
    align-items: center;
    flex-direction: column;
    margin-bottom: 1em;
    width: 100%;
    opacity: 0;
    transform: translateY(20px);
    transition: opacity 0.3s ease, transform 0.3s ease;
  }
  
  .faq-item.fade-in {
    opacity: 1;
    transform: translateY(0);
  }
  
  .pill-button {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 10px 20px;
    border: solid 1px var(--element-color-2);
    border-radius: 8px;
    color: var(--text-color);
    background-image: linear-gradient(
      to right,
      #00000000,
      var(--background-color-1t)
    );
    cursor: pointer;
    outline: none;
    width: 100%;
    max-width: 720px;
    transition: border 0.3s;
  }
  
  .pill-button:hover {
    border: solid 1px var(--highlight-color);
  }
  
  .plus-icon {
    font-weight: bold;
    margin-right: 10px;
  }
  
  .faq-answer {
    font-size: 0.9em;
    opacity: 0;
    text-align: left;
    border: none;
    background-image: linear-gradient(
      to right,
      var(--background-color-1t),
      #00000000
    );
    width: 100%;
    max-width: 720px;
    border-radius: 8px;
    overflow: hidden;
    max-height: 0;
    transition: all 0.3s ease-out;
  }
  
  .faq-answer.open {
    max-height: 500px;
    opacity: 0.9;
    border: solid 1px var(--highlight-color);
  }
  
  .answer-text {
    padding: 1em;
  }
  </style>
  