"""empty message

Revision ID: 63fb22cbe5ef
Revises: 804348085f99
Create Date: 2024-12-20 17:52:52.075149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63fb22cbe5ef'
down_revision = '804348085f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_completion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_rooms', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_completion', schema=None) as batch_op:
        batch_op.drop_column('completed_rooms')

    # ### end Alembic commands ###
