"""empty message

Revision ID: 677b09341aea
Revises: c1a09d011674
Create Date: 2024-06-26 01:18:31.718531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '677b09341aea'
down_revision = 'c1a09d011674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_room_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('library_door')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_door',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('library_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_name1', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('room_name2', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('state', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], name='library_door_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='library_door_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('library_room_state')
    # ### end Alembic commands ###
