"""empty message

Revision ID: 6962e9d76135
Revises: ba8819a34f40
Create Date: 2025-02-26 13:03:32.340009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '6962e9d76135'
down_revision = 'ba8819a34f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_lesson_progress')
    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_lessons', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('lesson_state', sa.Integer(), nullable=False))
        batch_op.drop_column('answered_questions')
        batch_op.drop_column('current_question_index')
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('current_question_index', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('answered_questions', sqlite.JSON(), nullable=False))
        batch_op.drop_column('lesson_state')
        batch_op.drop_column('num_lessons')

    op.create_table('user_lesson_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('library_id', sa.INTEGER(), nullable=False),
    sa.Column('room_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('current_question_index', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
