"""empty message

Revision ID: 6f6d3dea7f24
Revises: 63fb22cbe5ef
Create Date: 2025-02-25 20:08:25.490788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f6d3dea7f24'
down_revision = '63fb22cbe5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('library_completion', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('completed_rooms', sa.Text(), nullable=True))

    # with op.batch_alter_table('library_factoid', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('lesson_name', sa.String(length=200), nullable=False, server_default=''))
#  with op.batch_alter_table('library_factoid', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('lesson_name', sa.String(length=200), nullable=False, server_default=''))

    with op.batch_alter_table('user_lesson_progress', schema=None) as batch_op:
        batch_op.alter_column('lesson_name',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('current_question_index',
               existing_type=sa.INTEGER(),
               nullable=False, server_default='0')
        batch_op.drop_constraint(None, type_='foreignkey')

    # with op.batch_alter_table('user_lesson_progress', schema=None) as batch_op:
    #     # Add temporary column for type conversion
    #     batch_op.add_column(sa.Column('lesson_name_str', sa.String(length=200), nullable=True))

    #     # Convert Integer lesson_name to String lesson_name_str
    #     op.execute("UPDATE user_lesson_progress SET lesson_name_str = CAST(lesson_name AS TEXT)")

    #     # Drop old column and rename the new one
    #     batch_op.drop_column('lesson_name')
    #     batch_op.alter_column('lesson_name_str', new_column_name='lesson_name', nullable=False)

    #     # Ensure all existing NULL values in current_question_index are set to 0
    #     op.execute("UPDATE user_lesson_progress SET current_question_index = 0 WHERE current_question_index IS NULL")

    #     # Alter current_question_index to NOT NULL
    #     batch_op.alter_column('current_question_index',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_lesson_progress', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'lesson', ['lesson_name'], ['id'])
        batch_op.alter_column('current_question_index',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('lesson_name',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('library_factoid', schema=None) as batch_op:
        batch_op.drop_column('lesson_name')

    with op.batch_alter_table('library_completion', schema=None) as batch_op:
        batch_op.drop_column('completed_rooms')

    # ### end Alembic commands ###
