"""empty message

Revision ID: 77791963377c
Revises: 87c5c12acbdf
Create Date: 2024-07-18 14:48:49.404646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77791963377c'
down_revision = '87c5c12acbdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('language_difficulty', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('context', sa.String(length=200), nullable=True))
        batch_op.alter_column('library_topic',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)

    with op.batch_alter_table('library_factoid', schema=None) as batch_op:
        batch_op.alter_column('room_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)

    with op.batch_alter_table('library_question', schema=None) as batch_op:
        batch_op.alter_column('correct_choice',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=400),
               existing_nullable=False)

    with op.batch_alter_table('library_question_choice', schema=None) as batch_op:
        batch_op.alter_column('choice_text',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=400),
               existing_nullable=False)

    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.alter_column('room_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.alter_column('room_name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('library_question_choice', schema=None) as batch_op:
        batch_op.alter_column('choice_text',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('library_question', schema=None) as batch_op:
        batch_op.alter_column('correct_choice',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('library_factoid', schema=None) as batch_op:
        batch_op.alter_column('room_name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.alter_column('library_topic',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('context')
        batch_op.drop_column('language_difficulty')
        batch_op.drop_column('language')
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
