"""empty message

Revision ID: 87c5c12acbdf
Revises: 8750f891a884
Create Date: 2024-07-06 10:09:33.472688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87c5c12acbdf'
down_revision = '8750f891a884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_library_question_answer')
    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_question_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('answered_questions', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.drop_column('answered_questions')
        batch_op.drop_column('current_question_index')

    op.create_table('user_library_question_answer',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answered', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('answered_at', mysql.DATETIME(), nullable=True),
    sa.Column('choice_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['choice_id'], ['library_question_choice.id'], name='user_library_question_answer_ibfk_3'),
    sa.ForeignKeyConstraint(['question_id'], ['library_question.id'], name='user_library_question_answer_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_library_question_answer_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
