"""empty message

Revision ID: 8a8d8b0220ac
Revises: b7f83ec6f8f2
Create Date: 2024-07-20 15:53:07.890532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8d8b0220ac'
down_revision = 'b7f83ec6f8f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_completion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_completion', schema=None) as batch_op:
        batch_op.drop_column('is_complete')

    # ### end Alembic commands ###
