"""empty message

Revision ID: 8c2486640fd3
Revises: f0919ba3c71b
Create Date: 2023-12-08 01:52:06.515907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2486640fd3'
down_revision = 'f0919ba3c71b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared', sa.Boolean(), nullable=True))

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('shared')

    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.drop_column('shared')

    # ### end Alembic commands ###
