"""empty message

Revision ID: ba8819a34f40
Revises: ffbba5ee324c
Create Date: 2025-02-26 12:52:21.796280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8819a34f40'
down_revision = 'ffbba5ee324c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_lesson_progress', schema=None) as batch_op:
        batch_op.drop_column('lesson_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_lesson_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_name', sa.VARCHAR(length=200), nullable=False))

    # ### end Alembic commands ###
