"""check constrainst

Revision ID: ffbba5ee324c
Revises: 6f6d3dea7f24
Create Date: 2025-02-26 06:57:47.801822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffbba5ee324c'
down_revision = '6f6d3dea7f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_lesson_progress_new',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('user.id'), nullable=False),
        sa.Column('library_id', sa.Integer, sa.ForeignKey('library.id'), nullable=False),
        sa.Column('room_name', sa.String(length=200), nullable=False),
        sa.Column('lesson_name', sa.String(length=200), nullable=False),  # Changed from Integer -> String
        sa.Column('current_question_index', sa.Integer, nullable=False, server_default='0'),
    )

    # Copy data from the old table, ensuring no NULL values
    op.execute("""
        INSERT INTO user_lesson_progress_new (id, user_id, library_id, room_name, lesson_name, current_question_index)
        SELECT id, user_id, library_id, room_name, CAST(lesson_name AS TEXT), COALESCE(current_question_index, 0)
        FROM user_lesson_progress;
    """)

    # Drop the old table
    op.drop_table('user_lesson_progress')

    # Rename the new table to match the old one
    op.rename_table('user_lesson_progress_new', 'user_lesson_progress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_lesson_progress', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'lesson', ['lesson_name'], ['id'])
        batch_op.alter_column('current_question_index',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('lesson_name',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
