"""empty message

Revision ID: 02466440e8b1
Revises: 49b412f8485c
Create Date: 2025-09-13 13:34:57.695870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02466440e8b1'
down_revision = '49b412f8485c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('material_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'ready', 'error', name='test_status_enum'), server_default='pending', nullable=False),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mock_tests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_tests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('library_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('material_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'ready', 'error', name='mock_test_status_enum'), server_default=sa.text("'pending'::mock_test_status_enum"), autoincrement=False, nullable=False),
    sa.Column('questions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], name='mock_tests_library_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='mock_tests_pkey')
    )
    op.drop_table('tests')
    # ### end Alembic commands ###
