"""empty message

Revision ID: 02623a6eb1fe
Revises: cd87ff4470ca
Create Date: 2025-05-16 16:51:00.235975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02623a6eb1fe'
down_revision = 'cd87ff4470ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_membership_room_state", 'library_membership', ['user_id', 'library_id'], ['user_id', 'library_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
