"""Add points to LibraryMembership

Revision ID: 04abaaffb6a5
Revises: 4574b855de1c
Create Date: 2025-08-18 21:31:45.705251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04abaaffb6a5'
down_revision = '4574b855de1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_membership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_membership', schema=None) as batch_op:
        batch_op.drop_column('points')

    # ### end Alembic commands ###
