"""remove chat history

Revision ID: 0b7b64683db1
Revises: 04abaaffb6a5
Create Date: 2025-08-24 19:38:47.914522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b7b64683db1'
down_revision = '04abaaffb6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_history')
    with op.batch_alter_table('library_membership', schema=None) as batch_op:
        batch_op.drop_constraint('library_membership_library_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('library_membership_user_id_fkey', type_='foreignkey')

    with op.batch_alter_table('library_question', schema=None) as batch_op:
        batch_op.drop_constraint('fk_library_question_factoid_id', type_='foreignkey')

    with op.batch_alter_table('library_question_choice', schema=None) as batch_op:
        batch_op.drop_constraint('fk_library_question_choice_question_id', type_='foreignkey')

    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.drop_constraint('fk_section', type_='foreignkey')
        batch_op.drop_constraint('library_room_state_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('library_room_state_library_id_fkey', type_='foreignkey')

    with op.batch_alter_table('library_section', schema=None) as batch_op:
        batch_op.drop_constraint('library_section_unit_id_fkey', type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('auth_provider',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('auth_provider',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('library_section', schema=None) as batch_op:
        batch_op.create_foreign_key('library_section_unit_id_fkey', 'library_unit', ['unit_id'], ['id'])

    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('library_room_state_library_id_fkey', 'library', ['library_id'], ['id'])
        batch_op.create_foreign_key('library_room_state_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_section', 'library_section', ['section_id'], ['id'])

    with op.batch_alter_table('library_question_choice', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_library_question_choice_question_id', 'library_question', ['question_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('library_question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_library_question_factoid_id', 'library_factoid', ['factoid_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('factoid_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('library_membership', schema=None) as batch_op:
        batch_op.create_foreign_key('library_membership_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('library_membership_library_id_fkey', 'library', ['library_id'], ['id'])

    op.create_table('chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('system_role', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('challenge_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], name='chat_history_challenge_id_fkey'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name='chat_history_lesson_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='chat_history_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_history_pkey')
    )
    # ### end Alembic commands ###
