"""empty message

Revision ID: 10e7e166cce8
Revises: 7e48e816f729
Create Date: 2025-05-22 22:35:48.423497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e7e166cce8'
down_revision = '7e48e816f729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_section_position'), ['position'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_section_position'))

    # ### end Alembic commands ###
