"""empty message

Revision ID: 130355bed95c
Revises: b9ed3b5385bc
Create Date: 2025-05-14 11:44:36.942728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130355bed95c'
down_revision = 'b9ed3b5385bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('joined_at')

    # ### end Alembic commands ###
