"""library section and library unit

Revision ID: 1bc190781731
Revises: f2fd492e4c7c
Create Date: 2025-04-16 11:36:45.831035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc190781731'
down_revision = 'f2fd492e4c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], name='fk_library_unit_library_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['library_unit.id'], name='fk_library_section_unit_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library_factoid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_library_factoid_section_id', 'library_section', ['section_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_factoid', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('section_id')

    op.drop_table('library_section')
    op.drop_table('library_unit')
    # ### end Alembic commands ###
