"""empty message

Revision ID: 1e63449266e0
Revises: 553b1fdfb2f4
Create Date: 2025-05-04 08:52:16.411408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e63449266e0'
down_revision = '553b1fdfb2f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_membership',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'library_id')
    )
    with op.batch_alter_table('library', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.alter_column("user_id", new_column_name="owner_id")
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('join_code',
               existing_type=sa.VARCHAR(length=8),
               nullable=True,
               existing_server_default=sa.text("'ABCDEFGH'"))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_library_owner_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_library_user_id', 'user', ['user_id'], ['id'])
        batch_op.alter_column('join_code',
               existing_type=sa.VARCHAR(length=8),
               nullable=False,
               existing_server_default=sa.text("'ABCDEFGH'"))
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('owner_id')

    op.drop_table('library_membership')
    # ### end Alembic commands ###
