"""empty message

Revision ID: 250462cadd46
Revises: 77791963377c
Create Date: 2024-07-19 12:59:35.278815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250462cadd46'
down_revision = '77791963377c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('experience_points')

    # ### end Alembic commands ###
