"""empty message

Revision ID: 28046378fb26
Revises: e27dc8bcfa88
Create Date: 2025-05-24 18:35:28.770537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28046378fb26'
down_revision = 'e27dc8bcfa88'
branch_labels = None
depends_on = None

# a;lsdkfja;lsifhj;aekjfa
#  id INTEGER NOT NULL, 
#     section_id INTEGER, 
#     num_lessons INTEGER NOT NULL, 
#     lesson_state INTEGER NOT NULL, 
#     user_id INTEGER NOT NULL, 
#     library_id INTEGER NOT NULL, 
#     room_name VARCHAR(200) NOT NULL, 
#     PRIMARY KEY (id), 
#     CONSTRAINT fk_membership_room_state FOREIGN KEY(user_id, library_id) REFERENCES library_membership (user_id, library_id) ON DELETE CASCADE, 
#     CONSTRAINT uq_user_section UNIQUE (user_id, section_id), 
#     CONSTRAINT uq_library_user FOREIGN KEY(library_id) REFERENCES library (id) ON DELETE CASCADE, 
#     CONSTRAINT uq_section_user FOREIGN KEY(section_id) REFERENCES library_section (id) ON DELETE CASCADE, 
#     CONSTRAINT uq_user_id_room FOREIGN KEY(user_id) REFERENCES user (id) ON DELETE CASCADE, 
#     FOREIGN KEY(library_id) REFERENCES library (id), 
#     FOREIGN KEY(user_id) REFERENCES user (id)
# )
# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     # op.drop_table('library_room_state_new')DROP TABLE IF EXISTS _alembic_tmp_library_room_state;
#     # op.drop_table('_alembic_tmp_library_factoid')
#     # op.drop_table('_alembic_tmp_library_question_choice')
#     # op.drop_table('_alembic_tmp_library_room_state')
    
#     # Clean up invalid references before adding CASCADE constraints
#     op.execute("DELETE FROM library_room_state WHERE user_id NOT IN (SELECT id FROM user)")
#     op.execute("DELETE FROM library_room_state WHERE library_id NOT IN (SELECT id FROM library)")
#     op.execute("DELETE FROM library_room_state WHERE section_id NOT IN (SELECT id FROM library_section) AND section_id IS NOT NULL")
    
#     with op.batch_alter_table('library_room_state', schema=None) as batch_op:
#         batch_op.drop_constraint('fk_library_section_id', type_='foreignkey')
#         # batch_op.drop_constraint(None, type_='foreignkey')
#         # batch_op.drop_constraint(None, type_='foreignkey')
#         batch_op.create_foreign_key('uq_library_user', 'library', ['library_id'], ['id'], ondelete='CASCADE')
#         batch_op.create_foreign_key('uq_section_user', 'library_section', ['section_id'], ['id'], ondelete='CASCADE')
#         batch_op.create_foreign_key('uq_user_id_room', 'user', ['user_id'], ['id'], ondelete='CASCADE')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('library_room_state_new')DROP TABLE IF EXISTS _alembic_tmp_library_room_state;
    # op.drop_table('_alembic_tmp_library_factoid')
    # op.drop_table('_alembic_tmp_library_question_choice')
    # op.drop_table('_alembic_tmp_library_room_state')
    
    # purges invalid references before adding CASCADE constraints
    op.execute("""
      DELETE FROM library_room_state
       WHERE user_id NOT IN (SELECT id FROM "user")
          OR library_id NOT IN (SELECT id FROM library)
          OR (section_id IS NOT NULL
               AND section_id NOT IN (SELECT id FROM library_section))
          OR (user_id, library_id)
               NOT IN (SELECT user_id, library_id FROM library_membership)
    """)
    
    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        # batch_op.drop_constraint('fk_library_section_id', type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey') # need names for other constraints
        # batch_op.drop_constraint(None, type_='foreignkey')
        
        # goal here: drop old constraints, especially on (user_id, library_id)
        # batch_op.drop_constraint('fk_membership_room_state', type_='foreignkey')
        # batch_op.drop_constraint('fk_library_section_id',       type_='foreignkey')
        # batch_op.drop_constraint('fk_library_roomstate_library_id', type_='foreignkey')
        # batch_op.drop_constraint('fk_library_roomstate_user_id',    type_='foreignkey')

        # goal here: create new foreign constraints
        batch_op.create_foreign_key(
            'fk_membership_room_state',
            'library_membership',
            ['user_id', 'library_id'],
            ['user_id', 'library_id'],
            ondelete='CASCADE'
        )
        # single-column cascades
        batch_op.create_foreign_key(
            'fk_library_roomstate_user_id',
            'user', ['user_id'], ['id'], ondelete='CASCADE'
        )
        batch_op.create_foreign_key(
            'fk_library_roomstate_library_id',
            'library', ['library_id'], ['id'], ondelete='CASCADE'
        )
        batch_op.create_foreign_key(
            'fk_library_section_id',
            'library_section',
            ['section_id'], ['id'],
            ondelete='CASCADE'
        )

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'library', ['library_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id']) # teleport
        batch_op.create_foreign_key('fk_library_section_id', 'library_section', ['section_id'], ['id'])

    op.create_table('_alembic_tmp_library_room_state',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('num_lessons', sa.INTEGER(), nullable=False),
    sa.Column('lesson_state', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('library_id', sa.INTEGER(), nullable=False),
    sa.Column('room_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('section_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['library_section.id'], name='fk_library_section_id'),
    sa.ForeignKeyConstraint(['user_id', 'library_id'], ['library_membership.user_id', 'library_membership.library_id'], name='fk_membership_room_state', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'section_id', name='uq_user_section')
    )
    op.create_table('_alembic_tmp_library_question_choice',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('choice_text', sa.VARCHAR(length=400), nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=True),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['library_question.id'], name='fk_library_question_choice_question_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_alembic_tmp_library_factoid',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('library_id', sa.INTEGER(), nullable=True),
    sa.Column('room_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('factoid_content', sa.TEXT(), nullable=False),
    sa.Column('lesson_name', sa.VARCHAR(length=200), server_default=sa.text("('')"), nullable=False),
    sa.Column('section_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['library_section.id'], name='fk_library_roomstate_factoid_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_room_state_new',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('library_id', sa.INTEGER(), nullable=False),
    sa.Column('room_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('section_id', sa.INTEGER(), nullable=True),
    sa.Column('num_lessons', sa.INTEGER(), nullable=False),
    sa.Column('lesson_state', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['library_section.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'library_id'], ['library_membership.user_id', 'library_membership.library_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'section_id')
    )
    # ### end Alembic commands ###
