"""empty message

Revision ID: 2c5545a05a33
Revises: b700f079a420
Create Date: 2025-05-28 09:31:54.275952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5545a05a33'
down_revision = 'b700f079a420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute('PRAGMA foreign_keys = OFF')
    with op.batch_alter_table('library_factoid') as batch_op:
        # batch_op.drop_constraint('fk_library_roomstate_factoid_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_library_roomstate_factoid_id', 'library_section', ['section_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('library_room_state') as batch_op:
        # batch_op.drop_constraint('fk_section', type_='foreignkey')
        batch_op.create_foreign_key('fk_section_uq', 'library_section', ['section_id'], ['id'], ondelete='CASCADE')
    # op.execute('PRAGMA foreign_keys = ON')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_section', 'library_section', ['section_id'], ['id'])

    with op.batch_alter_table('library_factoid', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_library_roomstate_factoid_id', 'library_section', ['section_id'], ['id'])

    # ### end Alembic commands ###
