"""empty message

Revision ID: 35efa2bea274
Revises: 2c5545a05a33
Create Date: 2025-06-07 02:19:18.541216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = '35efa2bea274'
down_revision = '2c5545a05a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("PRAGMA foreign_keys=OFF;")
    
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=func.now(), nullable=False))
    op.execute("PRAGMA foreign_keys=ON;")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("PRAGMA foreign_keys=ON;")
    
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        op.execute("PRAGMA foreign_keys=OFF;")
        

    # ### end Alembic commands ###
