"""empty message

Revision ID: 448c5ba8097f
Revises: 28046378fb26
Create Date: 2025-05-25 12:27:54.199825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448c5ba8097f'
down_revision = '28046378fb26'
branch_labels = None
depends_on = None


def upgrade():
    
     
      
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_membership', schema=None) as batch_op:
        # Delete invalid records before creating cascade constraints
        # op.execute("PRAGMA foreign_keys=OFF;")
        op.execute("""
            DELETE FROM library_room_state
            WHERE user_id    NOT IN (SELECT id FROM "user")
                OR library_id NOT IN (SELECT id FROM library)
                OR (section_id IS NOT NULL
                    AND section_id NOT IN (SELECT id FROM library_section))
        """)
        op.execute("""
            DELETE FROM library_membership
            WHERE user_id    NOT IN (SELECT id FROM "user")
                OR library_id NOT IN (SELECT id FROM library);
        """)
        # op.execute("PRAGMA foreign_keys=ON;")
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('uq_membership_library', 'library', ['library_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('uq_membership_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # with op.batch_alter_table('library_room_state', schema=None) as batch_op:
    #     batch_op.drop_constraint('uq_user_section', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=25), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_section', ['user_id', 'section_id'])

    with op.batch_alter_table('library_membership', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'library', ['library_id'], ['id'])

    # ### end Alembic commands ###
