"""add timezone to user

Revision ID: 492fa842aa17
Revises: 4fc1a04fbbfc
Create Date: 2025-05-09 18:52:22.863375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492fa842aa17'
down_revision = '4fc1a04fbbfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('library_unit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_unit_position'), ['position'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        op.add_column('user',
        sa.Column('timezone', sa.String(length=50),
                  nullable=False, server_default='UTC')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_unit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_unit_position'))

    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
