"""empty message

Revision ID: 49b412f8485c
Revises: 4f81cae06d41
Create Date: 2025-09-13 13:14:08.024052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b412f8485c'
down_revision = '4f81cae06d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('material_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'ready', 'error', name='mock_test_status_enum'), server_default='pending', nullable=False),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mock_tests')
    status_enum = sa.Enum(name='mock_test_status_enum')
    status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
