"""empty message

Revision ID: 4f410d2c4ac0
Revises: 35efa2bea274
Create Date: 2025-06-14 10:47:34.865623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f410d2c4ac0'
down_revision = '35efa2bea274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        # POSTGRES
    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     # Add new columns
    #     batch_op.add_column(sa.Column('auth_provider', sa.String(length=20), nullable=True))
    #     batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
    
    # # Set default value for auth_provider for existing rows
    # op.execute("UPDATE \"user\" SET auth_provider = 'local' WHERE auth_provider IS NULL")
    
    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     # Create unique constraint for google_id
    #     batch_op.create_unique_constraint('contraint_google_id_user', ['google_id'])

    
    # SQLITE
    # op.execute("PRAGMA foreign_keys=OFF")
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Add new columns
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
    
    # Set default value for auth_provider for existing rows
    op.execute("UPDATE user SET auth_provider = 'local' WHERE auth_provider IS NULL")
    
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Create unique constraint for google_id
        batch_op.create_unique_constraint('contraint_google_id_user', ['google_id'])

    # op.execute("PRAGMA foreign_keys=ON")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('google_id')
        batch_op.drop_column('auth_provider')

    # ### end Alembic commands ###
