"""empty message

Revision ID: 4f81cae06d41
Revises: f22601e514ca
Create Date: 2025-09-13 12:45:13.514759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f81cae06d41'
down_revision = 'f22601e514ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     
    # Add the column allowing nulls first
    op.add_column('materials', 
                  sa.Column('added_to_course_path', sa.Boolean(), nullable=True))
    
    # Update existing rows
    op.execute("UPDATE materials SET added_to_course_path = false WHERE added_to_course_path IS NULL")
    
    # Then make it non-nullable
    op.alter_column('materials', 'added_to_course_path', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_column('added_to_course_path')

    # ### end Alembic commands ###
