"""empty message

Revision ID: 531628d20608
Revises: c243827dc24d
Create Date: 2025-05-27 16:32:22.298220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531628d20608'
down_revision = 'c243827dc24d'
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("PRAGMA foreign_keys=OFF;")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        # batch_op.drop_constraint('fk_library_section_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_section', 'library_section', ['section_id'], ['id'])
    # op.execute("PRAGMA foreign_keys=OFF;")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("PRAGMA foreign_keys=OFF;")
    
    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.drop_constraint('fk_section', type_='foreignkey')
        batch_op.create_foreign_key('fk_library_section_id', 'library_section', ['section_id'], ['id'], ondelete='CASCADE')
    # op.execute("PRAGMA foreign_keys=ON;")

    # ### end Alembic commands ###
