"""empty message

Revision ID: 54a3f0868831
Revises: 9c7833a99288
Create Date: 2024-08-14 20:15:59.570814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a3f0868831'
down_revision = '9c7833a99288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_tracking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('library_generated_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('room_generated_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guide', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.drop_column('guide')

    with op.batch_alter_table('ip_tracking', schema=None) as batch_op:
        batch_op.drop_column('room_generated_time')
        batch_op.drop_column('library_generated_time')

    # ### end Alembic commands ###
