"""empty message

Revision ID: 553b1fdfb2f4
Revises: abd94d010968
Create Date: 2025-05-03 23:47:04.477515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision = '553b1fdfb2f4'
down_revision = 'abd94d010968'
branch_labels = None
depends_on = None

# TODO COME BACK HERE IN THE MORNING
# apply join code migration, 
# then add join table for library and user
# then add functions for swapping public / private to regenerate codes / set them to null
# then on generation of libraries that are private, make sure they have join_codes
# then add ui ability to join private libraries / public libraries that you didn't create
    # basically in library browser, see all libraries
    # then add ability to leave libraries (later)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_code', sa.String(length=8)))

        # 2. back‑fill using a local helper
        # Session is already imported at the top of the file
        import secrets, string

        alphabet = string.ascii_uppercase + string.digits
        def new_code(length=8):
            return ''.join(secrets.choice(alphabet) for _ in range(length))

        bind = op.get_bind()
        session = Session(bind=bind)

        try:
            # Since we just created the column, start with an empty set of codes
            existing_codes = set()
            for lib_id, in session.execute(sa.text("SELECT id FROM library")):
                code = new_code()
                while code in existing_codes:
                    code = new_code()
                existing_codes.add(code)
                session.execute(sa.text(
                    "UPDATE library SET join_code = :code WHERE id = :id"),
                    {"code": code, "id": lib_id})
            session.commit()
        finally:
            session.close()

        # 3. add NOT NULL + UNIQUE + DEFAULT
        with op.batch_alter_table('library', schema=None) as batch_op:
            batch_op.alter_column('join_code',
                            nullable=False,
                            server_default=sa.text("'ABCDEFGH'"))   # dummy
            batch_op.create_unique_constraint(None, ['join_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('join_code')

    # ### end Alembic commands ###
