"""empty message

Revision ID: 553b1fdfb2f4
Revises: abd94d010968
Create Date: 2025-05-03 23:47:04.477515

"""
from alembic import op
import sqlalchemy as sa
from app.models import Library
from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision = '553b1fdfb2f4'
down_revision = 'abd94d010968'
branch_labels = None
depends_on = None

# TODO COME BACK HERE IN THE MORNING
# apply join code migration, 
# then add join table for library and user
# then add functions for swapping public / private to regenerate codes / set them to null
# then on generation of libraries that are private, make sure they have join_codes
# then add ui ability to join private libraries / public libraries that you didn't create
    # basically in library browser, see all libraries
    # then add ability to leave libraries (later)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_code', sa.String(length=8), nullable=True))

        bind = op.get_bind()
        session = Session(bind=bind)

        try:
            for lib in session.query(Library).filter(Library.join_code == None):
                lib.join_code = Library.generate_unique_code()
            session.commit()
        finally:
            session.close()
        
        op.alter_column('library', 'join_code',
                    nullable=False,
                    server_default=sa.text("'A22D2F3H'"))  # dummy default—Alembic

        batch_op.create_unique_constraint(None, ['join_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('join_code')

    # ### end Alembic commands ###
