"""add first_name and last_name to user

Revision ID: 7f5e10f1f1d0
Revises: 10e7e166cce8
Create Date: 2025-05-24 02:35:48.843738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5e10f1f1d0'
down_revision = '10e7e166cce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('is_favorited', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'library_id', name='uq_user_library_fav')
    )
    op.create_table('library_membership',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'library_id')
    )
    op.create_table('library_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id', 'position', name='uq_library_unit_position')
    )
    with op.batch_alter_table('library_unit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_unit_position'), ['position'], unique=False)

    op.create_table('library_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['library_unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'position', name='uq_unit_section_position')
    )
    with op.batch_alter_table('library_section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_section_position'), ['position'], unique=False)

    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('join_code', sa.String(length=8), nullable=True))
        batch_op.create_unique_constraint(None, ['join_code'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('library_factoid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.alter_column('library_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('room_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.create_foreign_key(None, 'library_section', ['section_id'], ['id'])

    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_user_section', ['user_id', 'section_id'])
        batch_op.create_foreign_key(None, 'library_membership', ['user_id', 'library_id'], ['user_id', 'library_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'library_section', ['section_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False))
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('streak_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('last_streak_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('highest_streak', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password_reset_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_reset_sent_at')
        batch_op.drop_column('password_reset_token')
        batch_op.drop_column('highest_streak')
        batch_op.drop_column('last_streak_date')
        batch_op.drop_column('streak_count')
        batch_op.drop_column('joined_at')
        batch_op.drop_column('timezone')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_user_section', type_='unique')
        batch_op.drop_column('section_id')

    with op.batch_alter_table('library_factoid', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('room_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('library_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('section_id')

    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('join_code')
        batch_op.drop_column('is_public')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('library_section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_section_position'))

    op.drop_table('library_section')
    with op.batch_alter_table('library_unit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_unit_position'))

    op.drop_table('library_unit')
    op.drop_table('library_membership')
    op.drop_table('library_favorites')
    # ### end Alembic commands ###
