"""empty message

Revision ID: 7f981508ecb6
Revises: 7263ddcf4b57
Create Date: 2023-12-16 16:47:04.359420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f981508ecb6'
down_revision = '7263ddcf4b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentor_name', sa.String(length=100), nullable=True))
        batch_op.drop_column('tutor_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tutor_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('mentor_name')

    # ### end Alembic commands ###
