"""empty message

Revision ID: 804348085f99
Revises: 54a3f0868831
Create Date: 2024-12-19 21:25:44.829736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804348085f99'
down_revision = '54a3f0868831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_completion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_completion', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
