"""empty message

Revision ID: 816886ffb28f
Revises: 8a8d8b0220ac
Create Date: 2024-07-22 01:35:46.871513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816886ffb28f'
down_revision = '8a8d8b0220ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_ip', sa.String(length=64), nullable=False),
    sa.Column('library_generated', sa.Boolean(), nullable=False),
    sa.Column('room_generated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_ip')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ip_tracking')
    # ### end Alembic commands ###
