"""empty message

Revision ID: 8750f891a884
Revises: 677b09341aea
Create Date: 2024-06-29 00:58:13.321607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8750f891a884'
down_revision = '677b09341aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_question_choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('choice_text', sa.String(length=100), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['library_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_choice', sa.String(length=100), nullable=False))

    with op.batch_alter_table('user_library_question_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('choice_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'library_question_choice', ['choice_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_library_question_answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('choice_id')

    with op.batch_alter_table('library_question', schema=None) as batch_op:
        batch_op.drop_column('correct_choice')

    op.drop_table('library_question_choice')
    # ### end Alembic commands ###
