"""empty message

Revision ID: 8d6647cfbf7b
Revises: be338bf68afb
Create Date: 2025-04-21 13:17:39.709588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6647cfbf7b'
down_revision = 'be338bf68afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_library_factoid_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_library_section_id', 'library_section', ['section_id'], ['id'])
        batch_op.drop_column('factoid_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('factoid_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_library_factoid_id', 'library_factoid', ['factoid_id'], ['id'])
        batch_op.drop_column('section_id')

    # ### end Alembic commands ###
