"""update user first_name last_name max length to 25

Revision ID: a9efc9ddd51d
Revises: 7f5e10f1f1d0
Create Date: 2025-05-24 02:35:01.873505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9efc9ddd51d'
down_revision = '7f5e10f1f1d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ip_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_ip', sa.String(length=64), nullable=False),
    sa.Column('library_generated', sa.Boolean(), nullable=False),
    sa.Column('library_generated_time', sa.DateTime(), nullable=True),
    sa.Column('room_generated', sa.Boolean(), nullable=False),
    sa.Column('room_generated_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_ip')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=True),
    sa.Column('last_name', sa.String(length=25), nullable=True),
    sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('mentor_name', sa.String(length=100), nullable=True),
    sa.Column('system_role', sa.String(length=100), nullable=True),
    sa.Column('profile', sa.Text(), nullable=True),
    sa.Column('ai_tutor_profile', sa.Text(), nullable=True),
    sa.Column('current_content', sa.String(length=500), nullable=True),
    sa.Column('experience_points', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('daily_request_count', sa.Integer(), nullable=True),
    sa.Column('last_request_time', sa.DateTime(), nullable=True),
    sa.Column('streak_count', sa.Integer(), nullable=False),
    sa.Column('last_streak_date', sa.Date(), nullable=True),
    sa.Column('highest_streak', sa.Integer(), nullable=False),
    sa.Column('violation_count', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmation_token', sa.String(length=100), nullable=True),
    sa.Column('confirm_sent_at', sa.DateTime(), nullable=True),
    sa.Column('password_reset_token', sa.String(length=100), nullable=True),
    sa.Column('password_reset_sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_name', sa.String(length=100), nullable=False),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('shared', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_name', sa.String(length=200), nullable=False),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('system_role', sa.String(length=100), nullable=True),
    sa.Column('shared', sa.Boolean(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('library_topic', sa.String(length=200), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('guide', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('language_difficulty', sa.String(length=50), nullable=False),
    sa.Column('context', sa.String(length=200), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('join_code', sa.String(length=8), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('room_names', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('join_code')
    )
    op.create_table('user_achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('system_role', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('completion_date', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('completed_rooms', sa.Text(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('is_favorited', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'library_id', name='uq_user_library_fav')
    )
    op.create_table('library_membership',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'library_id')
    )
    op.create_table('library_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id', 'position', name='uq_library_unit_position')
    )
    with op.batch_alter_table('library_unit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_unit_position'), ['position'], unique=False)

    op.create_table('user_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['library_unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'position', name='uq_unit_section_position')
    )
    with op.batch_alter_table('library_section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_section_position'), ['position'], unique=False)

    op.create_table('library_factoid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.Column('room_name', sa.String(length=200), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('lesson_name', sa.String(length=200), nullable=False),
    sa.Column('factoid_content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['library_section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_room_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(length=200), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('num_lessons', sa.Integer(), nullable=False),
    sa.Column('lesson_state', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['library_section.id'], ),
    sa.ForeignKeyConstraint(['user_id', 'library_id'], ['library_membership.user_id', 'library_membership.library_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'section_id', name='uq_user_section')
    )
    op.create_table('library_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factoid_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('correct_choice', sa.JSON(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['factoid_id'], ['library_factoid.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_question_choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('choice_text', sa.String(length=400), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['library_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('library_question_choice')
    op.drop_table('library_question')
    op.drop_table('library_room_state')
    op.drop_table('library_factoid')
    with op.batch_alter_table('library_section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_section_position'))

    op.drop_table('library_section')
    op.drop_table('user_action')
    with op.batch_alter_table('library_unit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_unit_position'))

    op.drop_table('library_unit')
    op.drop_table('library_membership')
    op.drop_table('library_favorites')
    op.drop_table('library_completion')
    op.drop_table('feedback')
    op.drop_table('chat_history')
    op.drop_table('user_achievement')
    op.drop_table('library')
    op.drop_table('lesson')
    op.drop_table('challenge')
    op.drop_table('user')
    op.drop_table('ip_tracking')
    op.drop_table('achievement')
    # ### end Alembic commands ###
