"""empty message

Revision ID: ae997c00aa7d
Revises: 8d6647cfbf7b
Create Date: 2025-04-21 14:17:27.535358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae997c00aa7d'
down_revision = '8d6647cfbf7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_factoid', schema=None) as batch_op:
        batch_op.alter_column('library_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('room_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_factoid', schema=None) as batch_op:
        batch_op.alter_column('room_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('library_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
