"""empty message

Revision ID: b700f079a420
Revises: 531628d20608
Create Date: 2025-05-27 16:44:24.405831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b700f079a420'
down_revision = '531628d20608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_library_room_state')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_library_room_state',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('section_id', sa.INTEGER(), nullable=True),
    sa.Column('num_lessons', sa.INTEGER(), nullable=False),
    sa.Column('lesson_state', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('library_id', sa.INTEGER(), nullable=False),
    sa.Column('room_name', sa.VARCHAR(length=200), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], name='fk_library_roomstate_library_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['library_section.id'], name='fk_library_section_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'library_id'], ['library_membership.user_id', 'library_membership.library_id'], name='fk_membership_room_state', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_library_roomstate_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
