"""add d highest_streak to user

Revision ID: b9ed3b5385bc
Revises: ec48488f2837
Create Date: 2025-05-09 20:49:03.386845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ed3b5385bc'
down_revision = 'ec48488f2837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highest_streak', sa.Integer(), server_default="0", nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('highest_streak')

    # ### end Alembic commands ###
