"""added factoid_id to libraryRoomState

Revision ID: be338bf68afb
Revises: 1bc190781731
Create Date: 2025-04-17 20:49:15.626027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be338bf68afb'
down_revision = '1bc190781731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('library_factoid', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
    #     batch_op.create_foreign_key('fk_library_roomstate_factoid_id', 'library_section', ['section_id'], ['id'])

    with op.batch_alter_table('library_factoid', schema=None) as batch_op:
        op.create_foreign_key(
        'fk_library_factoid_section_object',    # arbitrary, but unique
        'library_factoid',                  # source table
        'library_section',                  # target table
        ['section_id'],                     # local cols
        ['id'],                             # remote cols
    )

    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('factoid_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_library_factoid_id', 'library_factoid', ['factoid_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('factoid_id')

    with op.batch_alter_table('library_factoid', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('section_id')

    # ### end Alembic commands ###
