"""empty message

Revision ID: bfc64c349606
Revises: 02623a6eb1fe
Create Date: 2025-05-16 18:01:09.096806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc64c349606'
down_revision = '02623a6eb1fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_section', ['user_id', 'section_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_section', type_='unique')

    # ### end Alembic commands ###
