"""empty message

Revision ID: c243827dc24d
Revises: 448c5ba8097f
Create Date: 2025-05-27 11:49:25.481790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c243827dc24d'
down_revision = '448c5ba8097f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip the problematic constraint drop and just create the named constraint
    # SQLite will handle multiple constraints on the same column gracefully
    
    # op.execute("PRAGMA foreign_keys=OFF")
    # try:
    with op.batch_alter_table('library_section', schema=None) as batch_op:
        # Just create the new named foreign key constraint
        # Don't try to drop the existing unnamed one
        batch_op.create_foreign_key(
            'fk_library_section__unit_id', 
            'library_unit', 
            ['unit_id'], 
            ['id'], 
            ondelete='CASCADE'
        )
    # finally:
        # op.execute("PRAGMA foreign_keys=ON")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_section', schema=None) as batch_op:
        # Drop the named constraint we created
        batch_op.drop_constraint('fk_library_section__unit_id', type_='foreignkey')
        
        # Recreate an unnamed constraint (this is what was there originally)
        batch_op.create_foreign_key(None, 'library_unit', ['unit_id'], ['id'])
# ### end Alembic commands ###