"""empty message

Revision ID: cd87ff4470ca
Revises: 130355bed95c
Create Date: 2025-05-14 11:48:50.435878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd87ff4470ca'
down_revision = '130355bed95c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:

        conn = op.get_bind()
        conn.execute(sa.text("""
        UPDATE "user" 
        SET joined_at = CURRENT_TIMESTAMP 
        WHERE joined_at IS NULL
    """))

        batch_op.alter_column('joined_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('joined_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
