"""archive flag

Revision ID: d2355682a518
Revises: 8f7b9b5b4a3a
Create Date: 2025-09-05 16:38:52.952183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2355682a518'
down_revision = '8f7b9b5b4a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_membership', schema=None) as batch_op:
        # Add column as nullable first
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    # Update existing rows to have archived=False
    op.execute("UPDATE library_membership SET archived = false WHERE archived IS NULL")
    
    # Now make the column non-nullable
    with op.batch_alter_table('library_membership', schema=None) as batch_op:
        batch_op.alter_column('archived', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_membership', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
