"""empty message

Revision ID: e27dc8bcfa88
Revises: 04bd78af6616
Create Date: 2025-05-24 17:18:13.257218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e27dc8bcfa88'
down_revision = '04bd78af6616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_library_factoid')
    op.drop_table('library_room_state_new')
    op.drop_table('_alembic_tmp_library_room_state')
    op.drop_table('_alembic_tmp_library_question_choice')
    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.drop_constraint('fk_library_section_id', type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'library', ['library_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'library_section', ['section_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_room_state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'library', ['library_id'], ['id'])
        batch_op.create_foreign_key('fk_library_section_id', 'library_section', ['section_id'], ['id'])

    op.create_table('_alembic_tmp_library_question_choice',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('choice_text', sa.VARCHAR(length=400), nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=True),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['library_question.id'], name='fk_library_question_choice_question_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_alembic_tmp_library_room_state',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('num_lessons', sa.INTEGER(), nullable=False),
    sa.Column('lesson_state', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('library_id', sa.INTEGER(), nullable=False),
    sa.Column('room_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('section_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['library_section.id'], name='fk_library_section_id'),
    sa.ForeignKeyConstraint(['user_id', 'library_id'], ['library_membership.user_id', 'library_membership.library_id'], name='fk_membership_room_state', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'section_id', name='uq_user_section')
    )
    op.create_table('library_room_state_new',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('library_id', sa.INTEGER(), nullable=False),
    sa.Column('room_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('section_id', sa.INTEGER(), nullable=True),
    sa.Column('num_lessons', sa.INTEGER(), nullable=False),
    sa.Column('lesson_state', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['library_section.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'library_id'], ['library_membership.user_id', 'library_membership.library_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'section_id')
    )
    op.create_table('_alembic_tmp_library_factoid',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('library_id', sa.INTEGER(), nullable=True),
    sa.Column('room_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('factoid_content', sa.TEXT(), nullable=False),
    sa.Column('lesson_name', sa.VARCHAR(length=200), server_default=sa.text("('')"), nullable=False),
    sa.Column('section_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['library_section.id'], name='fk_library_roomstate_factoid_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
