"""streak countnt + last_streak_data

Revision ID: ec48488f2837
Revises: 492fa842aa17
Create Date: 2025-05-09 19:45:12.621480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec48488f2837'
down_revision = '492fa842aa17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_streak_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_streak_date')
        batch_op.drop_column('streak_count')

    # ### end Alembic commands ###
